TencentBlueKing/ci-repoAnalysis

- trivy/Dockerfile
> feat: 更新trivy到0.37.1 #7

- trivy/cmd/scan_executor.go
- trivy/constant/trivy.go
> feat: 支持Trivy扫描添加敏感信息规则文件 #12

- .github/workflows/deploy-bkrepo-trivy.yml
- trivy/Dockerfile
- trivy/README.md
> feat: 添加bkrpeo-trivy镜像构建流水线 #6

- analysis-tool-sdk-golang/README.md
- trivy/Dockerfile
- trivy/README.md
> feat: 更新trivy镜像版本 #17

- trivy/cmd/scan_executor.go
- trivy/constant/trivy.go
> feat: 支持Trivy自动下载漏洞库 #4

- dependency-check/README.md
- dependency-check/go.mod
- dependency-check/go.sum
- dependency-check/pkg/constant.go
- dependency-check/pkg/scan_executor.go
> feat: 支持dependency-check离线扫描 #23

- dependency-check/pkg/scan_executor.go
- trivy/README.md
- trivy/go.mod
- trivy/go.sum
- trivy/pkg/constant/trivy.go
- trivy/pkg/output.go
- trivy/pkg/scan_executor.go
> 支持trivy输出license扫描结果

- analysis-tool-sdk-golang/api/bkrepo.go
- analysis-tool-sdk-golang/object/manifest_v2.go
- analysis-tool-sdk-golang/object/tool_input.go
- analysis-tool-sdk-golang/util/downloader.go
- analysis-tool-sdk-golang/util/file.go
- analysis-tool-sdk-golang/util/file_test.go
- analysis-tool-sdk-golang/util/testdata/test-manifest.json
> bug: 修复镜像存在重复layer时拉取失败 #32

- dependency-check/go.mod
- dependency-check/go.sum
- filepath-search/go.mod
- filepath-search/go.sum
- trivy/go.mod
- trivy/go.sum
- trivy/pkg/scan_executor.go
> feat: 更新analysis-tool-sdk-golang版本到v0.0.15 #32

- trivy/pkg/constant/trivy.go
- trivy/pkg/scan_executor.go
> feat: 统一扫描器离线相关配置处理逻辑 #39

- .github/workflows/deploy-bkrepo-scancode.yml
- .github/workflows/deploy-scancode.yml
- scancode/Dockerfile
- scancode/README.md
- scancode/cmd/main.go
- scancode/go.mod
- scancode/go.sum
- scancode/pkg/executor.go
- scancode/pkg/executor_test.go
- scancode/pkg/output.go
- scancode/pkg/testdata/result.json
> feat: 增加scancode扫描工具 #21

- .github/workflows/deploy-golang-analysis-tool.yml
- analysis-tool-sdk-golang/go.mod
- dependency-check/go.mod
- filepath-search/Dockerfile
- filepath-search/go.mod
- scancode/go.mod
- trivy/go.mod
> depend: 更新golang版本到1.20 #42

- .github/workflows/deploy-golang-analysis-tool.yml
> chore: 修复go版本设置错误导致Action执行失败 #42

- analysis-tool-sdk-golang/api/bkrepo.go
- analysis-tool-sdk-golang/object/argument.go
> feat: 支持通过K8S Deployment执行分析任务 #45

- analysis-tool-sdk-golang/api/bkrepo.go
- analysis-tool-sdk-golang/api/bkrepo_test.go
- analysis-tool-sdk-golang/framework/executor.go
- analysis-tool-sdk-golang/object/argument.go
> feat: 增加--pull-retry参数设置重试拉取任务次数 #45

- standard-adapter/README.md
- standard-adapter/go.mod
- standard-adapter/go.sum
- standard-adapter/pkg/adapter.go
> feat: 支持将离线的标准扫描器转为在线扫描器 #48

- analysis-tool-sdk-golang/go.mod
- analysis-tool-sdk-golang/go.sum
- analysis-tool-sdk-golang/util/chunk.go
- analysis-tool-sdk-golang/util/chunk_test.go
> feat: 支持分片下载 #52

- analysis-tool-sdk-golang/framework/executor.go
- analysis-tool-sdk-golang/util/file.go
> feat: 支持配置不支持的文件名正则 #57

- analysis-tool-sdk-golang/object/argument.go
> feat: 增加heartbeat参数 #61

- analysis-tool-sdk-golang/api/bkrepo.go
- analysis-tool-sdk-golang/api/bkrepo_test.go
- analysis-tool-sdk-golang/framework/executor.go
> feat: 支持上报任务心跳 #61

- analysis-tool-sdk-golang/api/bkrepo.go
> feat: 取消输出toolInput到日志 #62

- analysis-tool-sdk-golang/api/bkrepo.go
- analysis-tool-sdk-golang/api/bkrepo_test.go
- analysis-tool-sdk-golang/framework/executor.go
- analysis-tool-sdk-golang/go.mod
- analysis-tool-sdk-golang/go.sum
- analysis-tool-sdk-golang/object/argument.go
- analysis-tool-sdk-golang/util/chunk.go
- analysis-tool-sdk-golang/util/chunk_test.go
- analysis-tool-sdk-golang/util/downloader.go
- analysis-tool-sdk-golang/util/log.go
- analysis-tool-sdk-golang/util/retryablehttp.go
> feat: 新增HTTP请求失败重试 #59

- analysis-tool-sdk-golang/api/bkrepo.go
- analysis-tool-sdk-golang/framework/executor.go
- analysis-tool-sdk-golang/object/tool_input.go
- analysis-tool-sdk-golang/util/cmd.go
- analysis-tool-sdk-golang/util/cmd_test.go
> feat: 支持设置扫描超时时间 #70

- dependency-check/pkg/scan_executor.go
> fix: 修复扫描带命名空间的npm制品时sed命令报错 #74
